#!/usr/bin/python3

import unittest

def format_number(number):
    assert (number >= 0), "number can not be negative"
    formated_number = ""
    for index, digit in enumerate(str(number)[::-1]):
        if (index + 1) % 3 == 0:
            formated_number = "," + digit + formated_number
        else:
            formated_number = digit + formated_number
    return formated_number

class TestSimple(unittest.TestCase):
    def test_simple(self):
        self.assertEqual(format_number(12345678),"12,345,678")

    def test_is_working(self):
        self.assertTrue(type(format_number(12345678) == str))

    def test_invalid_range(self):
        with self.assertRaises(AssertionError):
            format_number(-123456)

unittest.main(exit=False)
